вариант с if
Alex8185/paintboy pull request #3
Opened 2020-12-12 13:58 UTC by Alex8185

2020-12-12 23:27 UTC, Alexis220382 requested changes
Есть над чем ещё поработать, но прогресс однозначно есть.
Исправь, пожалуйста замечания и опять на ревью.
Спасибо

2020-12-12 23:27 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +            } else if (true) {
Тут можно написать просто `} else {` будет тоже самое.

2020-12-12 23:27 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +        for (int i = 0; i < 10; i++) {
Что обозначает цифра 10?

2020-12-12 23:27 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +import com.sun.deploy.security.SelectableSecurityManager;
Что это за импорт???

2020-12-12 23:27 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                }
Я так понимаю, что после того, как стало понятно, что чувак не в адеквате, то программа отправляет опять на вопрос да или нет. В задаче было сказано спросить три раза и если он ни разу правильно не ответил, то напечатать информационное сообщение и закончить программу

2020-12-13 10:30 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> +import com.sun.deploy.security.SelectableSecurityManager;
Он не активен, я не знаю откуда он взялся

2020-12-13 23:48 UTC, merged

2020-12-14 06:31 UTC, Alexis220382 reviewed
Ты считаешь, что не стоит выполнять рекомендации в ревью?

2020-12-14 06:31 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +import com.sun.deploy.security.SelectableSecurityManager;
Отличное объяснение, но абсолютно не убедительное.
По замечанию найдено какое-то непонятное оправдание и сделано ровным счетом ничего, за исключением того, что все смежено в главную ветку.