последний тикет
Alex8185/paintboy pull request #5
Opened 2020-12-18 22:11 UTC by Alex8185

Решил, что не помешает еще один класс, от лица которого будет говорить система. Т.к. у продавца и покупателя есть свой голос, а у магазине нет. Ну и что бы убрать из главного класса еще 2 строчки System.out.println

2020-12-19 11:31 UTC, Alexis220382 requested changes
1. С админом придумано круто
2. По абстракции я имел ввиду немного не то, надо исправить

2020-12-19 11:31 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> -                System.out.println("Продавец: Какие вас интересуют?");
Дык это, я просил сделать немного не то, я просил чтобы напечатанная строка добавляла сама инициатора разговора, ТО ЭСТ
когда вызывается `seller.speak("Добрый день!")`, то в консоли пишется `Продавец: Добрый день!`
НО
когда вызывается `client.speak("Добрый день!")`, то в консоли пишется `Клиент: Добрый день!`
тоже самое с админом

2020-12-19 11:31 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +        Human admin = new Admin();
Отличная идея. Круто придумано!!!

2020-12-20 13:49 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> -                System.out.println("Продавец: Какие вас интересуют?");
Made the class abstract.
Overridden methods.
I learned that: "overridden" this - "переопределил")))

2020-12-20 13:51 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> +        Human admin = new Admin();
I am pleased to)

2020-12-20 15:05 UTC, Alexis220382 requested changes
Надо доделывать.
Причины:
1. Невнимательность
2. Слишком большая уверенность в правильном решении
3. Как следствие из вышеуказанного..... приложение не протестировано

2020-12-20 15:05 UTC, Alexis220382 commented on src/main/java/by/shop/Admin.java
> +        System.out.println("Клиент: " + say);
В классе Admin говорит Клиент???

2020-12-20 15:05 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
>          seller.speak("Продавец: Добрый день!");
Тута не надо менять?

2020-12-20 15:05 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
>                  seller.speak("Продавец: Спасибо, и Вам хорошего дня!");
???

2020-12-20 15:05 UTC, Alexis220382 commented on src/main/java/by/shop/Seller.java
> +        System.out.println("Клиент: " + say);
И тута клиент говорит?

2020-12-20 15:28 UTC, Alexis220382 requested changes
Ну вот, другой разговор
Осталось одно маленькое исправление

2020-12-20 15:28 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
>          System.out.println("Введите: Да/Нет");
А тут не админ должен говорить?

2020-12-20 15:34 UTC, Alexis220382 approved these changes
Супер, спасибо, мержи!
В следующем пулл-реквесте, пожалуйста, поубирай лишние строки внутри переопределенных методов, может еще где-то найдешь, я вроде только тут увидел

2020-12-20 15:36 UTC, merged