array#1
Alex8185/paintboy pull request #6
Opened 2020-12-20 19:32 UTC by Alex8185

2020-12-20 20:13 UTC, Alexis220382 requested changes
Начало положено неплохое, но надо поработать.

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                System.out.println("Пожалуйста, сделайте выбор");
А кто это говорит?)))

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                Scanner scanner = new Scanner(System.in);
Создавать еще один объект сканера очень дорого, тем более, что их создастся столько, сколько раз выполнится цикл. Я думаю можно переиспользовать уже созданный, тот, на который указывает переменная `in`

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                int opNumber = Integer.parseInt(productNumber);
Я вижу, что переменная `opNumber` нигде не используется. Смысл ее создавать тогда?

И еще, когда я в ответе ввожу не цифру, то у меня программа выдает ошибку.
<img width="935" alt="Screenshot 2020-12-20 at 23 09 20" src="https://user-images.githubusercontent.com/12614685/102723366-68b68400-4318-11eb-9f71-9159e786bb32.png">
Я думаю, если клиент ее увидит, то он, мягко сказать, будет удивлен.

Удали, плз из этого пулл-реквеста строку `int opNumber = Integer.parseInt(productNumber);` ты еще коснешься этого по ходу и научишься обрабатывать эти ошибки, но это будет не в этой задаче

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/Admin.java
>      public void speak(String say) {
Вернемся немного назад. to say - это глагол, а нам нужна фраза, переданная в поведение speak. Возможно будет правильнее переменную назвать phrase, она будет более подходить своему названию

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                String[] products = new String[]{"НАСТЕННЫЕ", "НАРУЧНЫЕ", "НАСТОЛЬНЫЕ"};
В настоящий момент продукты зависли в воздухе, т.е. они ни кому и ни чему не принадлежат
Я так полагаю, что они должны быть где-то в магазине и, когда мы обращаемся к магазину, то мы можем из него обратиться и к продавцу и к продуктам.
Клиент, например, зашел и ушел, мы не можем его ассоциировать только с магазином, а продавца и товар можем

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                seller.speak("Это отличный выбор");
В задаче было написано немного по другому)))
```
После этого выводится в консоль следующая строка "Продавец: <good_name> это отличный выбор."
```
Где наименование выбранного Клиентом товара в ответе продавца???

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
>              if (line.equals("Да")) {
Если клиент отвечает "да", а не "Да", то система говорит о не корректном ответе. Интерфейс должен быть user friendly и эта ситуация может увести у нас клиента. Мы должны сделать все для того, чтобы клиент купил у нас товар.
Подсказка: есть еще метод в классе String, который решает эту задачу.

2020-12-20 20:13 UTC, Alexis220382 commented on src/main/java/by/shop/App.java
> +                seller.speak("Это отличный выбор");
При предложении сделать выбор товара, я ввел 8 и, О ЧУДО, я увидел ответ, что это отличный выбор)))
Обманывать клиентов не хорошо🙂

2020-12-20 20:55 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> +                System.out.println("Пожалуйста, сделайте выбор");
Аристарх Людвигович)
Исправлено

2020-12-20 21:12 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> +                Scanner scanner = new Scanner(System.in);
Удалил дублирующий сканер, и убедился, что действительно действие первого сканера распространяется и в "глубину" цикла. Это ли не чудо...

2020-12-20 21:48 UTC, Alex8185 commented on src/main/java/by/shop/Admin.java
>      public void speak(String say) {
Переименовал

2020-12-21 22:07 UTC, Alex8185 commented on src/main/java/by/shop/App.java
> +                int opNumber = Integer.parseInt(productNumber);
Строку удалил.
Попробовал исправить ошибку с не цифрой оператором ветвления if, но что то пошло не так. Оставил эту затею.

2021-01-12 16:08 UTC, merged